name: Deploy React Project to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install project dependencies
        run: |
          npm install
        
      - name: Create .env file
        run: |
          echo "Creating .env file..."
          echo "${{ secrets.ENV }}" > .env

      - name: Build React project
        run: |
          npm run build
      
      
          
      - name: List files before deployment
        run: |
          ls -la
  
        # Step 4: Sync files to cPanel via FTP
      - name: Sync files to development
        uses: SamKirkland/FTP-Deploy-Action@v4.2.0
        with:
          server: ftp.trimworldwide.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

      - name: Clean up
        run: echo "Clean up step"
