name: Deploy React Project to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - name: Install project dependencies
        run: |
          npm install
        
      - name: Create .env file
        run: |
          echo "Creating .env file..."
          echo "${{ secrets.ENV }}" > .env

      - name: Build React project
        run: |
          npm run build
      
      
          
      - name: List files before deployment
        run: |
          ls -la
      
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
        # Step 4: Sync files to cPanel via FTP
      - name: Sync files to development
        env:
          server: ftp.trimworldwide.com
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          cd build # Adjust this if your build output directory is different
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD $server; mirror -R -e -x .git/ ./"

      - name: Clean up
        run: echo "Clean up step"
