name: Deploy React Project to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          
      - name: Install project dependencies
        run: npm install
        
      - name: Build React project
        run: |
          npm run build
          
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
        
      - name: Deploy to Shared Hosting using FTP
        env:
          FTP_USERNAME: ${{ secrets.STAGE_FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.STAGE_FTP_PASSWORD }}
          FTP_HOST: ftp.trimworldwide.com
        run: |
          cd build # Adjust this if your build output directory is different
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R -e -x .git/ ./"
      - name: Clean up
        run: echo "Clean up step"
